on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 7,15,23 * * *'
jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          git pull
          git config --global user.email "kazuhitoyokoi@nodered.jp"
          git config --global user.name "Kazuhito Yokoi"
          curl -O https://catalogue.nodered.org/catalogue.json
          npm install fs-extra
          node create-catalogue.js catalogue.json
          git add docs/*
          git commit -m "Update catalogue"
          git push
