on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3,9,15,21 * * *'
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          git pull
          git config --global user.email "kazuhitoyokoi@nodered.jp"
          git config --global user.name "Kazuhito Yokoi"
          curl -O https://catalogue.nodered.org/catalogue.json
          npm install --prefix bin fs-extra
          node bin/create-catalogue.js catalogue.json docker
          git add docs/*
          git commit -m "Update catalogue"
          git push
  os:
    needs: docker
    strategy:
      max-parallel: 1
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: |
          git pull
          git config --global user.email "kazuhitoyokoi@nodered.jp"
          git config --global user.name "Kazuhito Yokoi"
          curl -O https://catalogue.nodered.org/catalogue.json
          npm install --prefix bin fs-extra
          node bin/create-catalogue.js catalogue.json
          git add docs/*
          git commit -m "Update catalogue"
          git push
  join:
    needs: os
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          git pull
          git config --global user.email "kazuhitoyokoi@nodered.jp"
          git config --global user.name "Kazuhito Yokoi"
          node bin/join-catalogue.js
          git add docs/*
          git commit -m "Update catalogue"
          git push
