on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -O https://catalogue.nodered.org/catalogue.json
          cat catalogue.json | jq '.modules|.[]|.id+"@"+.version' | head | xargs -I{} sh docker.sh {}
          echo "{ \"name\": \"Catalogue for docker\", \"updated_at\": \"`node -e 'console.log(new Date())'`\", \"modules\": `jq -s . *.tmp` }" | jq . > docs/docker.json
          git config --global user.email "kazuhitoyokoi@nodered.jp"
          git config --global user.name "Kazuhito Yokoi"
          git add docs/docker.json
          git commit -m "Update catalogue"
          git push
