on:
  push:
    branches: [ main ]
jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -O https://catalogue.nodered.org/catalogue.json
          cat catalogue.json | jq '.modules|.[]|.id+"@"+.version' | head -n 3 | xargs -I{} sh docker.sh {}
          ls
          echo "{ \"name\": \"Catalogue for docker\", \"updated_at\": \"`node -e 'console.log(new Date())'`\", \"modules\": `jq -s . *.tmp` }" | jq . > docs/docker.json
          cat docs/docker.json
          git config --global user.email "kazuhitoyokoi@nodered.jp"
          git config --global user.name "Kazuhito Yokoi"
          git add docs/docker.json
          git commit -m "Update catalogue"
          git push
