name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          curl -O https://catalogue.nodered.org/catalogue.json
          cat catalogue.json | jq '.modules|.[]|.id+"@"+.version' | xargs -I{} sh container.sh {}
          echo '{"name": "Catalogue for Node-RED container","updated_at": "`node -e 'console.log(new Date())'`","modules":' > docs/container.json
          cat *.tmp | jq -s . >> docs/container.json
          echo '}' >> docs/container.json
          git config --global user.email "kazuhitoyokoi@nodered.jp"
          git config --global user.name "Kazuhito Yokoi"
          git add docs/container.json
          git commit -m "Add zip file which includes the latest Node-RED"
          git push
