on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 15 * * *'
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo npm install node-red-contrib-matrix-chat@0.7.0
          npm install node-red-contrib-matrix-chat@0.7.0
          echo dir
          dir
          echo del /S /Q node_modules package.json package-lock.json
          del /S /Q node_modules
          echo dir
          dir
