on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 15 * * *'
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.email "kazuhitoyokoi@nodered.jp"
          git config --global user.name "Kazuhito Yokoi"
          curl -O https://catalogue.nodered.org/catalogue.json
          npm install fs-extra
          node create-catalogue.js catalogue.json > docs/windows.json
          git add docs/windows.json
          git commit -m "Update catalogue"
          git push
